---
- name: Add harbor helm repository
  kubernetes.core.helm_repository:
    name: harbor
    repo_url: https://helm.goharbor.io

- name: Install harbor
  kubernetes.core.helm:
    name: harbor
    kubeconfig: ../files/do-kubeconfig.yaml
    chart_ref: harbor/harbor
    create_namespace: yes
    release_namespace: harbor
    values_files:
      - ../files/values.yaml